Use pyproject.toml instead of setup.py
HIT-ReFreSH/PyMobileSuit pull request #11
Opened 2024-11-03 09:30 UTC by Jessica870506

2022211800高端 2022211801耿艺彤 2022211804周密密

2024-11-03 16:53 UTC, FerdinandSu requested changes
Most of the code seems to be OK, but the changes on PrintUnit.py and importation of colorama is confusing. Please make an explanation or change them back.

2024-11-03 16:53 UTC, FerdinandSu commented on src/ReFreSH/MobileSuit/PrintUnit.py
Why colorama is imported? If colour is no more required, remove “import colour”.

2024-11-04 02:03 UTC, Jessica870506 commented
have removed colorama and changed them back

2024-11-04 02:23 UTC, FerdinandSu approved these changes

2024-11-04 02:23 UTC, merged